apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    nf: upf
  ports:
    - protocol: UDP
      port: 2152
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.56.103